export const Books = [
    {
        id: 1,
        title: "1984",
        authorName: "George Orwell",
        publishDate: "1949-06-08",
        pages: 328,
        description: "A dystopian tale of a totalitarian regime where Big Brother watches all, delving into themes of surveillance, freedom, and rebellion.",
        coverImage: "https://m.media-amazon.com/images/I/81fcLJo+FNL._SY466_.jpg",
    },
    {
        id: 2,
        title: "Brave New World",
        authorName: "Aldous Huxley",
        publishDate: "1932-08-30",
        pages: 311,
        description: "A vision of a controlled society ruled by technology, consumerism, and stability at the expense of individuality and emotion.",
        coverImage: "https://m.media-amazon.com/images/I/51CWnp7rtlL._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 3,
        title: "Fahrenheit 451",
        authorName: "Ray Bradbury",
        publishDate: "1953-10-19",
        pages: 194,
        description: "In a future where books are banned, a 'fireman' tasked with burning them questions censorship and the worth of knowledge.",
        coverImage: "https://m.media-amazon.com/images/I/71AupHJxqiL._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 4,
        title: "Animal Farm",
        authorName: "George Orwell",
        publishDate: "1945-08-17",
        pages: 112,
        description: "An allegorical tale of farm animals who revolt against their owner, mirroring the Russian Revolution and totalitarian regimes.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbcV6pI9ZZJWzqsH2QHLYbnGlzdr5c0XbgvA&s"
    },
    {
        id: 5,
        title: "The Handmaid's Tale",
        authorName: "Margaret Atwood",
        publishDate: "1985-09-01",
        pages: 311,
        description: "In a theocratic society where women’s rights are abolished, this story delves into themes of power, gender, and resistance.",
        coverImage: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1488552336i/34454589.jpg",
    },
    {
        id: 6,
        title: "Do Androids Dream of Electric Sheep?",
        authorName: "Philip K. Dick",
        publishDate: "1968-03-01",
        pages: 210,
        description: "A bounty hunter faces ethical dilemmas as he 'retires' rogue androids, exploring humanity in a post-apocalyptic world.",
        coverImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/DoAndroidsDream.png/285px-DoAndroidsDream.png",
    },
    {
        id: 7,
        title: "The Road",
        authorName: "Cormac McCarthy",
        publishDate: "2006-09-26",
        pages: 287,
        description: "A father and son traverse a desolate, post-apocalyptic world, showcasing survival, hope, and familial bonds.",
        coverImage: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1600241424i/6288.jpg",
    },
    {
        id: 8,
        title: "The Giver",
        authorName: "Lois Lowry",
        publishDate: "1993-04-26",
        pages: 240,
        description: "Jonas discovers dark truths about his seemingly perfect society, challenging conformity and exploring emotions.",
        coverImage: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1342493368i/3636.jpg",
    },
    {
        id: 9,
        title: "Lord of the Flies",
        authorName: "William Golding",
        publishDate: "1954-09-17",
        pages: 224,
        description: "Stranded boys attempt self-governance on an island, descending into chaos and revealing humanity’s darker nature.",
        coverImage: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327869409i/7624.jpg"
    },
    {
        id: 10,
        title: "Never Let Me Go",
        authorName: "Kazuo Ishiguro",
        publishDate: "2005-03-03",
        pages: 288,
        description: "Children at a boarding school uncover the haunting truth about their existence in this emotional tale.",
        coverImage: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1353048590i/6334.jpg",
    },
];
